export { git, GitError } from './git/exec.js'
export { snapshot, pinSnapshot, unpinReview } from './git/snapshot.js'
export type { Snapshot } from './git/snapshot.js'
export { resolveBase } from './git/range.js'
export type { BaseResolution, BaseSource } from './git/range.js'
export { addWorktree, attachWorktree, removeWorktree } from './git/worktree.js'
export { computeChanges, hunkPath } from './narrate/diff.js'
export type { FileChange, Hunk, ChangeKind } from './narrate/diff.js'
export type { Assignment, Chapter, ChapterPlanner, Plan, PlanContext } from './narrate/plan.js'
export { RulePlanner } from './narrate/rule-planner.js'
export { buildPlan } from './narrate/build-plan.js'
export { DEFAULT_RULES, REPO_RULES_PATH, loadRules, rulesFingerprint, validateRules } from './narrate/rules.js'
export type { NarrativeRules, LoadRulesOptions } from './narrate/rules.js'
export { DEFAULT_PAIR_RULES, canonicalCandidates, canonicalPath } from './narrate/pair.js'
export type { PairRules } from './narrate/pair.js'
export { SCANNER_VERSION, buildDepGraph, languageOf, scanImports } from './narrate/deps.js'
export type { DepGraph, SourceLang } from './narrate/deps.js'
export { topoOrder } from './narrate/order.js'
export type { OrderResult } from './narrate/order.js'
export { segment } from './narrate/segment.js'
export type { Segment, SegmentInput } from './narrate/segment.js'
export { EMPTY_REGISTRY, REGISTRY_FILE, readRegistry, updateRegistry, writeRegistry } from './narrate/registry.js'
export type { ChapterRecord, ChapterStatus, Registry, UpdateInput } from './narrate/registry.js'
export { ANNOTATIONS_FILE, migrateAnchors, pinnedByAnnotations, readAnnotations, writeAnnotations } from './narrate/anchors.js'
export type { Annotation, AnnotationFile, AnnotationState } from './narrate/anchors.js'
export { validatePlan } from './narrate/validate.js'
export type { ValidationIssue, ValidationCode } from './narrate/validate.js'
export { composeContent } from './narrate/compose.js'
export { replay } from './narrate/replay.js'
export type { ReplayResult } from './narrate/replay.js'
export { verify, VerifyError } from './narrate/verify.js'
export { narrate } from './narrate/run.js'
export type { NarrateOptions, NarrateResult, NarrateChanges, NarrateNoChanges } from './narrate/run.js'
export { toCodeTours } from './tour/codetour.js'
export type { CodeTour, CodeTourStep } from './tour/codetour.js'
export { repoId, newReviewId, reviewRoot, repoStateDir } from './state/paths.js'
export { listReviews, latestReview, readPlan } from './state/reviews.js'
export type { ReviewEntry } from './state/reviews.js'
export { cleanReviews } from './state/cleanup.js'
export type { CleanupResult } from './state/cleanup.js'
export { comparePlans } from './narrate/compare.js'
export type { PlanDiff, FileMove } from './narrate/compare.js'
export { planOnly } from './narrate/run.js'
export type { PlanOnlyResult } from './narrate/run.js'
export { nextRound } from './git/snapshot.js'
