export { git, GitError } from './git/exec.js'
export { snapshot, pinSnapshot, unpinReview } from './git/snapshot.js'
export type { Snapshot } from './git/snapshot.js'
export { resolveBase } from './git/range.js'
export type { BaseResolution, BaseSource } from './git/range.js'
export { addWorktree, attachWorktree, removeWorktree } from './git/worktree.js'
export { computeChanges } from './narrate/diff.js'
export type { FileChange, Hunk, ChangeKind } from './narrate/diff.js'
export type { Chapter, ChapterPlanner, Plan, PlanContext } from './narrate/plan.js'
export { RulePlanner, classifyPath } from './narrate/rule-planner.js'
export { validatePlan } from './narrate/validate.js'
export type { ValidationIssue, ValidationCode } from './narrate/validate.js'
export { composeContent } from './narrate/compose.js'
export { replay } from './narrate/replay.js'
export type { ReplayResult } from './narrate/replay.js'
export { verify, VerifyError } from './narrate/verify.js'
export { narrate } from './narrate/run.js'
export type { NarrateOptions, NarrateResult } from './narrate/run.js'
export { toCodeTours } from './tour/codetour.js'
export type { CodeTour, CodeTourStep } from './tour/codetour.js'
export { repoId, newReviewId, reviewRoot } from './state/paths.js'
